app:
  domain:
    dev: ${DEV_DOMAIN}
    prod: ${PROD_DOMAIN}
  
  roles:
    secured-role: ${SECURED_ROLE}
    public-role: ${PUBLIC_ROLE}
    prospect-role: ${PROSPECT_ROLE}
  
  jwt:
    secret: ${JWT_SECRET}
  
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${ECR_REGION}
    bucket-name:
      dev: ${DEV_BUCKET_NAME}
      prod: ${PROD_BUCKET_NAME}
    ses:
      source-email: ${AWS_SES_EMAIL}
  
  email:
    templates:
      password-reset: ${PASSWORD_RESET_EMAIL_TEMPLATE}
      thanks: ${THANKS_EMAIL_TEMPLATE}
      contact-response: ${CONTACT_RESPONSE_EMAIL_TEMPLATE}
      email-verification: ${EMAIL_VERIFICATION_TEMPLATE}
      booking-confirmation-email: ${BOOKING_CONFIRMATION_EMAIL_TEMPLATE}
  
  stripe:
    api-key: ${STRIPE_API_KEY}
    endpoint-secret: ${STRIPE_ENDPOINT_SECRET}

  contact:
    company-email: ${GOALGLO_EMAIL}
    company-phone-number: ${GOALGLO_PHONE_NUMBER}

  spring:
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:dev}